export const productSelect = {
  id: true,
  type: true,
  url: true,
  name: true,
  nameSource: true,
  imageUrl: true,
  hasCustomImage: true,
  store: true,
  currency: true,
  archived: true,
  lastCheckedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;
